### ISSUE TITLE
Use stable version of Composer package arangodb-php

### ISSUE THREAD

**Issue by sandrokeil** [prooph/arangodb-snapshot-store#2]
The develop branch is used, because to use the latest version. If a stable version was released, we should update the `composer.json` file. Maybe the package name will also change from `triagens/arangodb` to `arangodb/arangodb`.

**Comment by sandrokeil** [comment]
[ArangoDB 3.2](https://www.arangodb.com/2017/07/arangodb-3-2-rocksdb-pregel-fault-tolerant-foxx-satellite-collections/) is available, so a new [ArangoDB PHP driver](https://github.com/arangodb/arangodb-php/releases) should be released soon.

**Comment by prolic** [comment]
Is this issue still valid @sandrokeil ?

**Comment by sandrokeil** [comment]
Closing it in favor of #14
